repos:

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        #language_version: python3.8 # Should be a command that runs python3.6+

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
        #language_version: python3.8

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ['--config=tox.ini', '--exit-zero']
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins, 
          flake8-commas, 
          flake8-comprehensions, 
          flake8-logging-format,
          flake8-print,
          flake8-simplify,
          #flake8-spellcheck,
          flake8-rst-docstrings,
          flake8-bugbear,
          #flake8-eradicate,
          pandas-vet,
        ]
        #language_version: python3.8
#
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.6.0
#    hooks:
#      - id: pylint
#        language_version: python3.8
